name = "bulktrack-ai-worker"
main = "src/index.ts"
compatibility_date = "2024-12-17"

[env.production]
name = "bulktrack-ai-worker-production"

[[d1_databases]]
binding = "DB"
database_name = "bulktrack-production"
database_id = "your-database-id"

[[queues.consumers]]
queue = "ai-analysis"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 2
visibility_timeout_ms = 300000

[[queues.consumers]]
queue = "pattern-detection"
max_batch_size = 20
max_batch_timeout = 10
max_retries = 3
visibility_timeout_ms = 120000

[ai]
binding = "AI"

[vars]
ENVIRONMENT = "development"